# Generated by Django 6.0.6 on 2026-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('Empleado', 'Empleado'), ('Asignación', 'Asignación'), ('Sistema', 'Sistema')], default='Sistema', max_length=20),
            preserve_default=False,
        ),
    ]
