# Generated by Django 6.0.6 on 2026-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Laptop', 'Laptop'), ('Celular', 'Celular')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
